va_display_drm: Allow VGEM for WSL2
intel/libva-utils pull request #308
Opened 2023-02-10 17:58 UTC by sivileri

Signed-off-by: Sil Vilerino <sivileri@microsoft.com>

Related https://github.com/intel/libva/pull/688

2023-02-10 21:43 UTC, sivileri commented
@dvrogozh this change makes `vainfo --display drm` work along with the recently approved https://github.com/intel/libva/pull/688

2023-02-10 21:59 UTC, dvrogozh requested changes

2023-02-10 21:59 UTC, dvrogozh commented on common/va_display_drm.c
> +        if (!strncmp(version->name, "vgem", 4)
As suggested by @evelikov in other review:
```
if (!strncmp(version->name, "vgem", 4) && (uname(&sysinfo) >= 0) &&
    !strstr(sysinfo.release, "WSL")) {
```

2023-02-10 22:45 UTC, dvrogozh approved these changes
looks good

2023-02-11 10:15 UTC, evelikov commented on common/va_display_drm.c
> -        if (!strncmp(version->name, "vgem", 4)) {
Do you mind adding a small comment:
On normal Linux platforms we do not want vgem. Yet WSL uses vgem, while also providing a fallback VA driver (see libva for more)

2023-02-15 11:52 UTC, XinfengZhang approved these changes

2023-02-15 14:49 UTC, merged